site_name: kuantian.zhang's Web
site_description: kuantian.zhang 的个人博客
site_author: kuantian.zhang
site_url: https://zhangkuantian.github.io/

repo_url: https://github.com/zhangkuantian/zhangkuantian.github.io
repo_name: zhangkuantian/blog

theme:
  name: material
  custom_dir: overrides
  favicon: assets/favicon.webp
  icon:
    logo: octicons/code-review-16
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: 进入夜间模式
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: 进入日间模式
  language: 'zh'
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zhangkuantian
      name: AkibaArisa on GitHub
    - icon: fontawesome/brands/steam
      link: https://steamcommunity.com/id/akibaarisa
      name: AkibaArisa on Steam

extra_css:
  - stylesheets/custom.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/waifu/autoload.js  # 十分耗时，放在最后加载

plugins:
  - search
  - blogging:
      locale: zh_CN
      dirs:
        - blog
      features:
        tags: {}
      theme:
        name: card
        time_format: '%Y-%m-%d %H:%M:%S'
        meta_time_format: '%Y-%m-%d %H:%M:%S'
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_datetime
  - glightbox:
      draggable: false

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
